### ISSUE TITLE
/opt/freifunk/update.sh wirft fehler

### ISSUE THREAD

**Issue by DO1JLR** [ffbsee/ansible#20]
```bash
root@gw03 <22:51>  0  ~ 
$ /opt/freifunk/update.sh 
Removed 0 old nodes
Traceback (most recent call last):
  File "./map-backend.py", line 666, in main
    AlfredParser.parse_line(line.strip(), nodes, links)
  File "./map-backend.py", line 167, in parse_line
    properties = decompress.decompress(properties.encode('raw-unicode-escape'),64*1024).decode('utf-8')
zlib.error: Error -3 while decompressing data: invalid bit length repeat
Removed 0 old nodes
Traceback (most recent call last):
  File "/opt/freifunk/v2_map-backend.py", line 671, in main
    AlfredParser.parse_line(line.strip(), nodes, links)
  File "/opt/freifunk/v2_map-backend.py", line 167, in parse_line
    properties = decompress.decompress(properties.encode('raw-unicode-escape'),64*1024).decode('utf-8')
zlib.error: Error -3 while decompressing data: invalid bit length repeat
update done
```

```
root@meta ~ # /opt/freifunk/update.sh
Removed 0 old nodes
Traceback (most recent call last):
  File "./map-backend.py", line 666, in main
    AlfredParser.parse_line(line.strip(), nodes, links)
  File "./map-backend.py", line 167, in parse_line
    properties = decompress.decompress(properties.encode('raw-unicode-escape'),64*1024).decode('utf-8')
zlib.error: Error -3 while decompressing data: invalid bit length repeat
Removed 0 old nodes
Traceback (most recent call last):
  File "/opt/freifunk/v2_map-backend.py", line 671, in main
    AlfredParser.parse_line(line.strip(), nodes, links)
  File "/opt/freifunk/v2_map-backend.py", line 167, in parse_line
    properties = decompress.decompress(properties.encode('raw-unicode-escape'),64*1024).decode('utf-8')
zlib.error: Error -3 while decompressing data: invalid bit length repeat
Removed 0 old nodes
Traceback (most recent call last):
  File "/opt/freifunk/map-backend_ffrgb.py", line 813, in main
    AlfredParser.parse_line(line.strip(), nodes, links)
  File "/opt/freifunk/map-backend_ffrgb.py", line 167, in parse_line
    properties = decompress.decompress(properties.encode('raw-unicode-escape'),64*1024).decode('utf-8')
zlib.error: Error -3 while decompressing data: invalid bit length repeat
update done
```

**Comment by mart-ffbsee** [comment]
wart 5-10 minuten, dann wirfts keine fehler mehr.
